---

# Server settings
server_username: deploy
timezone: "America/Montevideo"

# Cabal
cabal_install_version: 3.8.1.0
cabal_base_url: "https://downloads.haskell.org"
cabal_install_url: "{{ cabal_base_url }}/~cabal/cabal-install-{{ cabal_install_version }}/cabal-install-{{ cabal_install_version }}-x86_64-linux-deb10.tar.xz"

# GHC
ghc_install_version: 8.10.7
ghc_install_url: "https://downloads.haskell.org/~ghc/{{ ghc_install_version }}/ghc-{{ ghc_install_version }}-x86_64-deb9-linux.tar.xz"

# Libsodium
libsodium_github_url: "https://github.com/input-output-hk/libsodium"
libsodium_version_tag:  "66f017f1"

# Libsecp256k1
secp256k1_github_url: "https://github.com/bitcoin-core/secp256k1"
secp256k1_tag: "ac83be33"

# Cluster configuration
cardano_node_config: "mainnet"
#cardano_node_config: "testnet"

# Cardano
cardano_node_build_number: "113437330"
cardano_github_repo: "https://github.com/input-output-hk/cardano-node.git"
cardano_github_release_url: "https://api.github.com/repos/input-output-hk/cardano-node/releases/latest"
cardano_config_download: "https://book.world.dev.cardano.org/environments/{{ cardano_node_config }}/"
cardano_version_tag: "8.1.2"
cardano_install_dir: "/opt/cardano/cnode"
cardamo_cli_path: "cardano-cli"
cardano_config_dir: "{{ cardano_install_dir }}/configuration"
cardano_scripts_dir: "{{ cardano_install_dir }}/scripts"
cardano_config_filename: "config.json"
cardano_byron_genesis_filename: "byron-genesis.json"
cardano_shelley_genesis_filename: "shelley-genesis.json"
cardano_alonzo_genesis_filename: "alonzo-genesis.json"
cardano_topology_filename: "topology.json"
cardano_node_type: "block"

# Alonzo Configuration
cardano_alonzo_genesis: "https://hydra.iohk.io/build/7416228/download/1/{{ cardano_node_config }}-alonzo-genesis.json"
cardano_shelly_test_config: "https://hydra.iohk.io/build/{{ node_build_num }}/download/1/{{ cardano_node_config }}-config.json"
cardano_byron_test_genesis: "https://hydra.iohk.io/build/{{ node_build_num }}/download/1/{{ cardano_node_config }}-byron-genesis.json"
cardano_shelly_test_genesis: "https://hydra.iohk.io/build/{{ node_build_num }}/download/1/{{ cardano_node_config }}-shelley-genesis.json"
cardano_shelly_test_topology: "https://hydra.iohk.io/build/{{ node_build_num }}/download/1/{{ cardano_node_config }}-topology.json"
cardano_magic_prefix: "--testnet-magic"


# Monitoring tools
cardano_community_cncli_uri: "https://github.com/AndrewWestberg/cncli/releases/download/"
cardano_community_cncli_tag: "v4.0.4"
cardano_community_cncli_version: "4.0.4"
cardano_community_gliveview: "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/gLiveView.sh"
cardano_community_gliveview_env: "https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/env" 

# Cardano submit API (optional)
cardano_submit_api: false
cardano_submit_api_config_dir: "cardano-submit-api/config"
cardano_submit_api_config_filename: "tx-submit-mainnet-config.yaml"
cardano_tx_submit_mainnet_config: "https://raw.githubusercontent.com/input-output-hk/cardano-node/master/cardano-submit-api/config/tx-submit-mainnet-config.yaml"
cardano_tx_submit_service: "tx-api.service"
cardano_tx_submit_description: "Cardano TX Submit API"
cardano_tx_submit_syslog_id: "cardano-tx-api"
cardano_tx_submit_address: "0.0.0.0"
cardano_tx_submit_port: "8090"
overwrite_policy: "--overwrite-policy=always"

# Pool metadata
cardano_pool_name: "Gperez Cardano Pool"
cardano_pool_description: "A democratic Cardano Pool"
cardano_pool_ticker: "My Pool ticker symbol"
cardano_pool_homepage: "https://cardano.gperez.link/"
cardano_pool_extended: "https://cardano.gperez.link/extendedMetaData.json"
